[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
position_management_system = "9bca4kbDn7uyQWQaqfKpe8hCdbBh6KqJFNbkzwHhieC3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/test-wallet-2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

